# Generated by Django 5.2.8 on 2025-12-21 21:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_rename_role_membership_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('WORKSPACE_CREATED', 'Workspace Created'), ('WORKSPACE_UPDATED', 'Workspace Updated'), ('WORKSPACE_DELETED', 'Workspace Deleted'), ('INVITE_SENT', 'Invite Sent'), ('INVITE_ACCEPTED', 'Invite Accepted'), ('MEMBER_JOINED', 'Member Joined')], max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workspaces.workspaces')),
            ],
        ),
    ]
