# Generated by Django 5.2.8 on 2025-12-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileasset',
            old_name='upload',
            new_name='uploaded_by',
        ),
        migrations.RenameField(
            model_name='fileattachment',
            old_name='FileAsset',
            new_name='file_asset',
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
