# Generated by Django 5.2.8 on 2025-12-24 17:41

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_rename_upload_fileasset_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileasset',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
