# Generated by Django 5.2.8 on 2025-12-24 17:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=30)),
                ('source_id', models.UUIDField()),
                ('content', models.TextField()),
                ('embedding', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='workspaces.workspaces')),
            ],
        ),
    ]
